site_name: Orbit-Q 
site_description: Official hardware documentation and resources for Orbit-Q by NTX Systems.
site_author: NTX Systems Pvt. Ltd.
site_url: https://ntxsystems.github.io/Orbit-Q/

theme:
  name: material
  palette:
    primary: indigo
    accent: deep orange

nav:
  - Home: README.md
  - Tutorials:
      - MCU Cards:
          - STM32F405:
              - Arduino IDE:
                  - Getting Started: "Tutorials/MCU-Cards/STM32F405/Arduino-IDE/Getting Started/text.md"
