site_name: Orbit-Q Modular Development Board
site_description: Official hardware documentation and resources for Orbit-Q by NTX Systems.
site_author: NTX Systems Pvt. Ltd.
site_url: https://ntxsystems.github.io/Orbit-Q/

repo_url: https://github.com/ntxsystems/Orbit-Q
repo_name: ntxsystems/Orbit-Q

theme:
  name: material
  logo: images/Orbit-Q-logo.png
  favicon: images/Orbit-Q-logo.png
  palette:
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.top
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.code.copy
    - content.tooltips
  font:
    text: Inter
    code: JetBrains Mono
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: README.md
  - Gallery: images/readme.md
  - Datasheet: "Orbit-Q Datasheet.pdf"
  - Tutorials:
      - MCU Cards:
          - STM32F103:
              - Arduino IDE:
                  - Getting Started: "Tutorials/MCU-Cards/STM32F103/Arduino-IDE/Getting Started/text.md"
          - STM32F405:
              - Arduino IDE:
                  - Getting Started: "Tutorials/MCU-Cards/STM32F405/Arduino-IDE/Getting Started/text.md"
                  - Blink Example: "Tutorials/MCU-Cards/STM32F405/Arduino-IDE/Blink-Example/text.md"
                  - Upload Methods: "Tutorials/MCU-Cards/STM32F405/Arduino-IDE/Upload-Methods/text.md"
                  - WS2812B LED Example: "Tutorials/MCU-Cards/STM32F405/Arduino-IDE/WS2812B-RGB-LED-Example/text.md"
                  - Oled Display Example: "Tutorials/MCU-Cards/STM32F405/Arduino-IDE/Oled-Display-Example/text.md"
